language: objective-c
osx_image: xcode9
xcode_project: PPal.xcodeproj # path to your xcodeproj folder
xcode_scheme: PPal
xcode_sdk: iphonesimulator11.0

before_install:
- brew install tailor
script:
- tailor PPal --except=trailing-whitespace --max-severity=error
- tailor PPalTests --except=trailing-whitespace --max-severity=error
- xcodebuild test -project PPal.xcodeproj -scheme PPal -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.0'

notifications:
  webhooks: https://injabie3.moe/travis-ci-cmpt275.php
